spbm/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
import debug_toolbar

from spbm.apps.society.views import PermissionDeniedView

handler403 = PermissionDeniedView.as_view()

urlpatterns = [
    # Django Debug Toolbar always included to make testing less fragile
    url(r"^__debug__/", include(debug_toolbar.urls)),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("spbm.apps.accounts.urls")),
    url(r"^", include("spbm.apps.society.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spbm/apps/society/models.py
from decimal import Decimal

from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import Sum, F
from django.urls import reverse
from django.utils import six
from django.utils.functional import lazy
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _, ugettext

mark_safe_lazy = lazy(mark_safe, six.text_type)


class Society(models.Model):
    """
    Model for student societies -- and other members -- of SPF.
    """

    class Meta:
        verbose_name = _('society')
        verbose_name_plural = _('societies')

    name = models.CharField(max_length=100,
                            verbose_name=_('name'))
    shortname = models.CharField(max_length=10,
                                 verbose_name=_('abbreviated name'))
    invoice_email = models.EmailField(default="",
                                      verbose_name=_('invoice e-mail'))
    default_wage = models.DecimalField(max_digits=10, decimal_places=2,
                                       default=Decimal("160"), verbose_name=_('default wage per hour'))
    logo = models.FileField(null=True, blank=True, verbose_name=_('logo'))

    def __str__(self):
        return self.shortname


class Worker(models.Model):
    """
    Model for student -- and other types of -- workers.
    """

    class Meta:
        verbose_name = _('worker')
        verbose_name_plural = _('workers')

    societies = models.ManyToManyField(Society,
                                       through='Employment',
                                       related_name='workers')
    name = models.CharField(max_length=1000,
                            verbose_name=_('name'),
                            help_text=_('Full name, with first name first.'))
    address = models.CharField(max_length=1000,
                               verbose_name=_('address'),
                               help_text=_('Full address including postal code and area.'))
    account_no = models.CharField(max_length=20,
                                  blank=True,
                                  null=True,
                                  verbose_name=_('account no.'),
                                  help_text=_('Norwegian bank account number, no periods, 11 digits.'))
    person_id = models.CharField(max_length=20,
                                 blank=True,
                                 null=True,
                                 unique=True,
                                 verbose_name=_('person ID'))
    norlonn_number = models.IntegerField(blank=True,
                                         null=True,
                                         unique=True,
                                         verbose_name=_("norl&oslash;nn number"),
                                         help_text=mark_safe_lazy(_(
                                             "Employee number in the wage system, Norl&oslash;nn. " +
                                             "<strong>Must</strong> exist and be correct!")))

    def get_absolute_url(self):
        return reverse('worker-view', args=[str(self.id)])

    def __str__(self):
        return self.name + " (#" + str(self.id) + ")"


class Employment(models.Model):
    """
    Through-model for the relationship between a worker and a society.
    :keyword !Society
    :keyword !Worker
    """

    class Meta:
        unique_together = ('worker', 'society')

    worker = models.ForeignKey(Worker,
                               on_delete=models.CASCADE)
    society = models.ForeignKey(Society,
                                on_delete=models.PROTECT)
    active = models.BooleanField(default=True, null=False, verbose_name=_('active'),
                                 help_text=_('Check off if the worker is still actively working.'))


class Invoice(models.Model):
    """
    Model for the invoices associated with closing a period of events.
    """

    class Meta:
        verbose_name = _('invoice')
        verbose_name_plural = _('invoices')
        unique_together = ('period', 'society')
        permissions = (
            ('close_period', "Can close periods to generate invoices"),
            ('mark_paid', "Can mark invoices as paid")
        )

    class InvoiceManager(models.Manager):
        def get_queryset(self):
            """ select_related() to improve performance """
            return super().get_queryset().select_related()

    """ The society the invoice belongs to """
    society = models.ForeignKey(Society, verbose_name=_('society'), related_name="invoices", on_delete=models.PROTECT)
    """ A unique invoice number, which SHOULD be reflected in the external invoice system """
    invoice_number = models.IntegerField(verbose_name=_('invoice number'), unique=True)
    """ The date for which the period is valid """
    period = models.DateField(verbose_name=_('period'))
    """ Status of received payment """
    paid = models.BooleanField(verbose_name=_('invoice paid'), default=False)
    """ User who created the invoice, i.e. closed the invoice period """
    created_by = models.ForeignKey(User, help_text=_('User which closed the period the invoice belongs to.'),
                                   on_delete=models.PROTECT, null=True, default=None)

    objects = InvoiceManager()

    def get_total_cost(self):
        """
        Calculates the cost for an event, including the percentage fee.
        :return: Decimal of total event cost, including the fee.
        """
        # FIXME: Decimal issues: should we add output_field=models.FloatField?
        total_costs = Decimal(
            self.events.all()
                .aggregate(total_cost=Sum('sum_costs'))
                .get('total_cost'))

        fee = self.get_fee_cost(total_costs)

        return (total_costs + fee).quantize(Decimal('.01'))

    def get_total_event_cost(self):
        """
        Calculates the cost for the invoice in regards to the events alone.
        :return: Decimal of total event cost, not including the fee.
        """
        total_event_costs = Decimal(
            self.events.all()
                .aggregate(total_event_cost=Sum('sum_costs'))
                .get('total_event_cost'))

        return total_event_costs.quantize(Decimal('.01'))

    @classmethod
    def get_fee_cost(cls, event_total_cost):
        return (Decimal(event_total_cost) * Decimal(settings.SPBM.get('fee'))).quantize(Decimal('.01'))

    def __str__(self):
        return ugettext("Invoice #{id}: {period} {society}").format(id=str(self.invoice_number),
                                                                    society=str(self.society.shortname),
                                                                    period=str(self.period))


class Event(models.Model):
    """
    Model for events, bookings and other sorts of works performed by societies.
    """

    class Meta:
        verbose_name = _('event')
        verbose_name_plural = _('events')

    class EventManager(models.Manager):
        def get_queryset(self):
            """ Changed manager to include sum of costs and hours, plus related society by default """
            return (super().get_queryset().select_related()
                    .prefetch_related('shifts__worker')
                    .annotate(sum_costs=Sum(F('shifts__hours') * F('shifts__wage'),
                                            output_field=models.DecimalField(decimal_places=2)),
                              sum_hours=Sum('shifts__hours',
                                            output_field=models.DecimalField(decimal_places=2))))

    society = models.ForeignKey(Society, null=False, verbose_name=_('society'), related_name="society",
                                on_delete=models.PROTECT)
    name = models.CharField(max_length=100,
                            verbose_name=_('name'),
                            help_text=_('Name or title describing the event.'))
    date = models.DateField(verbose_name=_('event date'),
                            help_text=_('The date of the event in the format of <em>YYYY-MM-DD</em>.'))
    registered = models.DateField(auto_now_add=True,
                                  editable=False,
                                  verbose_name=_('registered'),
                                  help_text=_('Date of event registration.'))

    ''' 'processed' and 'invoice' are very tightly coupled together.
    Why exactly are both needed? Any invoice is processed on an exact date. If it shouldn't be part of an invoice,
    then it is not really processed anyway. '''
    # TODO: Create migration from processed to purely invoice, alt. from field to property method.
    processed = models.DateField(null=True,
                                 blank=True,
                                 verbose_name=_('processed'))

    # If you've got an invoice, maybe it shouldn't be allowed to be deleted.
    # However, do we have some other good ways of doing it? :/ I mean, *easy* ways of doing it?
    # Let's be difficult with ourselves. Don't delete the invoices, just remove the invoice from the event!
    invoice = models.ForeignKey(Invoice,
                                null=True,
                                blank=True,
                                on_delete=models.PROTECT,
                                related_name="events",
                                verbose_name=_('invoice'))

    objects = EventManager()

    @property
    def hours(self):
        """ Dynamically get the number of hours registered on an event """
        hours = Decimal(0)
        for shift in self.shifts.all():
            hours += shift.hours
        hours = hours.quantize(Decimal(".01"))
        return hours

    hours.fget.short_description = _("Total hours")

    @property
    def cost(self):

spbm/apps/society/views/workers.py
from django.contrib import messages as msg
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.translation import ugettext as _
from django.views.generic import UpdateView, CreateView, DetailView, DeleteView, FormView, TemplateView
from django.views.generic.edit import FormMixin

from spbm.apps.society.forms.workers import WorkerForm, WorkerEditForm, WorkerPersonIDForm
from spbm.apps.society.models import Society, Worker, Employment
from spbm.helpers.auth import user_allowed_society, user_society
from spbm.helpers.mixins import LoginAndPermissionRequiredMixin


@login_required
def redirect_society(request):
    """
    Simply passes all requests to the index for the society, despite its lack of content.
    """
    return redirect('workers-overview', society_name=request.user.spfuser.society.shortname)


class IndexWorker(LoginRequiredMixin, FormMixin, TemplateView):
    template_name = 'workers/index.jinja'
    form_class = WorkerPersonIDForm
    raise_exception = True  # show "Permission denied" rather than redirect to login page

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if not request.user.has_perm('society.add_employment'):
            return self.handle_no_permission()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        # Get the society from the keyword arguments, via URLconf
        society = get_object_or_404(Society, shortname=self.kwargs['society_name'])

        workers = Worker.objects.filter(employment__society=society) \
            .select_related().order_by("norlonn_number").distinct()
        context = super().get_context_data()
        context.update({
            'inactive_workers': workers.filter(employment__active=False),
            'active_workers': workers.filter(employment__active=True),
            'society': society,
        })
        return context

    def form_valid(self, form):
        """
        Evaluate the add-worker-by-national-ID form, and redirect appropriately.
        """
        worker = Worker.objects.filter(person_id=form.cleaned_data['person_id']).first()
        society = user_society(self.request)
        if worker and society in worker.societies.all():
            msg.info(self.request,
                     _('{worker} is already associated with your society {society}.')
                     .format(worker=worker, society=society))
            return redirect(worker)
        elif worker:
            employment = Employment(society=society, worker=worker)
            employment.save()
            msg.success(self.request,
                        _('The worker {worker} has been successfully associated as employed with {society}.')
                        .format(worker=worker, society=society))
            return redirect(worker)
        else:
            msg.info(self.request,
                     _('There is no worker with that national ID. You may create one now.'))
            return redirect('worker-create', society_name=society, nid=form.cleaned_data['person_id'])


class CreateWorker(LoginAndPermissionRequiredMixin, CreateView):
    template_name = 'workers/create.jinja'
    permission_required = 'society.add_worker'
    permission_denied_message = _('You do not have the required permission to create workers.')
    model = Worker
    form_class = WorkerForm

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if self.kwargs.get('nid') and form.fields['person_id'].initial is None:
            form.fields['person_id'].initial = self.kwargs.get('nid')
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'society': get_object_or_404(Society, shortname=self.kwargs['society_name']),
        })
        return context

    def form_valid(self, form):
        society = get_object_or_404(Society, shortname=self.kwargs['society_name'])

        self.object = form.save()
        employment = Employment(worker=self.object, society=society)
        employment.save()
        return super().form_valid(form)


class UpdateWorker(LoginAndPermissionRequiredMixin, UpdateView):
    """
    Provides a simple editing interface for workers using #UpdateView.
    """
    model = Worker
    template_name = 'workers/edit.jinja'
    form_class = WorkerEditForm
    success_url = reverse_lazy('workers')
    raise_exception = True
    permission_denied_message = _('You do not have the permission to edit workers belonging to other societies.')

    def has_permission(self):
        return self.request.user.has_perm('society.change_worker') \
               and user_allowed_society(self.request.user, self.get_object().societies)


class ViewWorker(LoginAndPermissionRequiredMixin, DetailView):
    template_name = 'workers/view.jinja'
    permission_denied_message = _('You do not have the permission to view workers belonging to other societies.')
    model = Worker

    def has_permission(self):
        # FIXME: Creates an overhead of two extra queries per viewing :(
        return user_allowed_society(self.request.user, self.get_object().societies)


class DeleteWorker(LoginAndPermissionRequiredMixin, DeleteView):
    template_name = 'delete.jinja'
    model = Worker
    success_url = reverse_lazy('workers')
    queryset = Worker.objects.filter(shifts__isnull=True)

    def has_permission(self):
        return self.request.user.has_perm('society.delete_worker') \
               and user_allowed_society(self.request.user, self.get_object().societies)


"""
Workflow for adding a user, which ties into CreateWorker.
"""


class AddWorker(LoginAndPermissionRequiredMixin, FormView):
    template_name = 'workers/add.jinja'
    permission_required = 'society.add_worker'
    form_class = WorkerPersonIDForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'society': get_object_or_404(Society, shortname=self.kwargs['society_name']),
        })
        return context

    def form_valid(self, form):
        national_id = form.cleaned_data['person_id']
        worker = Worker.objects.filter(person_id=national_id).first()
        if worker:
            return HttpResponseRedirect(reverse_lazy('worker-associate', args=[worker.pk]))
        else:
            return HttpResponseRedirect(reverse_lazy('worker-create',
                                                     kwargs={'society_name': self.kwargs['society_name'],
                                                             'nid': national_id}))

templates/workers/add.jinja
{% extends 'base.jinja' %}
{% if worker %}
{% set title = _('Associate existing worker') %}
{% else %}
{% set title = _('Add worker') %}
{% endif %}

{% block content %}
{%- if not worker -%}
<form class="form-horizontal" method="post" action="">
    {% csrf_token %}
    {% autoescape off %}

    {# Include and enumerate through the main form #}
    {% include 'form-loop.jinja' %}

    {# Add the submit and cancel buttons #}
    <div class="form-group">
        {% block buttons -%}
            <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn-success">
                    {{ _('Create new or associate with existing worker') }}
                </button>
            </div>
        {%- endblock buttons %}
    </div>
    {% endautoescape %}
</form>
{%- else -%}
{%- endif -%}
{% endblock %}

templates/workers/associate.jinja
{% extends 'base.jinja' %}
{% set title = _('Associate existing worker') %}

{% block content %}
<p>
    {%- trans -%}
        This is the worker associated with the given national ID-number.
    {%- endtrans -%}
</p>



<form class="form-horizontal" method="post" action="">
    {% csrf_token %}
    {% autoescape off %}

    {{ object }}
    {# Include and enumerate through the main form #}
    {% include 'form-loop.jinja' %}

    {# Add the submit and cancel buttons #}
    <div class="form-group">
        {% block buttons -%}
            <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn-primary">
                    {{ _('Associate %(worker)s with %(society)s', worker=worker.name, society=user.spfuser.society) }}
                </button>
            </div>
        {%- endblock buttons %}
    </div>
    {% endautoescape %}
</form>
{% endblock %}

templates/workers/create.jinja
{% extends 'base.jinja' %}
{% set title = _('Add worker') %}

{% block content %}
<form class="form-horizontal" method="post" action="">
    {% csrf_token %}
    {% autoescape off %}

    {# Include and enumerate through the main form #}
    {% include 'form-loop.jinja' %}

    {# Add the submit and cancel buttons #}
    <div class="form-group">
        {% block buttons -%}
            <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn-success">
                    {{ _('Create worker') }}
                </button>
                <a href="{{ url('workers') }}" title="{{ _('Cancel creating this event') }}" class="btn btn-warning">
                    {{ _('Cancel creating this worker') }}
                </a>
            </div>
        {%- endblock buttons %}
    </div>
    {% endautoescape %}
</form>
{% endblock %}

templates/workers/edit.jinja
{% extends "base.jinja" %}
{% set title = _('Edit worker') %}

{% block content %}
    <style>
        .new {
            padding: 10px;
        }
    </style>
    <form class="form-horizontal" action="" method="POST">
        {% csrf_token %}
        {% include 'form-loop.jinja' %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn-primary" type="submit">
                    {{ _('Save changes') }}
                </button>
                <a href="{{ url("workers") }}" title="{{ _('Cancel editing this worker') }}" class="btn btn-warning">
                    {{ _('Cancel editing & changes') }}
                </a>
            </div>
        </div>
    </form>
{% endblock %}

templates/workers/index.jinja
{% extends "base.jinja" %}
{% set title = _("Workers") %}

{# TODO: Simplify form for national ID lookup, possibly with an include or a macro #}
{% block toolbar %}
    {%- if user.has_perms(['society.add_worker', 'society.add_employment']) -%}
        {%- set disabled_attr = '' -%}
        {%- set title = _('Enter a national ID to find an existing worker, or to create a new one.') -%}
    {%- else -%}
        {%- set disabled_attr = ' disabled="disabled"' -%}
        {%- set title = _('You do not have the permission to associate or add new workers.') -%}
    {%- endif -%}
    <form method="post" action="" {%- if form.errors %}class="has-error"{% endif %}>
        {% csrf_token %}
        {% for field in form %}
            <label class="sr-only" for="id_person_id" {{- disabled_attr }}>{{ _("National ID") }}</label>
            <div class="input-group" title="{{ title }}">
                <input id="id_person_id" name="person_id" type="text" class="form-control" {{- disabled_attr }}
                       placeholder="{{ _("National ID number...") }}">
                <span class="input-group-btn">
                    <button class="btn btn-success" type="submit" {{- disabled_attr }}>
                        <span class="glyphicon glyphicon-search"></span>
                        {{ _("Find or add worker") }}</button>
                            <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false"><span
                                    class="caret"></span></button>
                            <ul class="dropdown-menu dropdown-menu-right">
                                <li><a href="{{ url('worker-create', society_name=society) }}"
                                        title="{{ _("Go directly to the creation form") }}">
                                    {{ _("Add worker") }}</a></li>
                            </ul>
                </span>
            </div>
            {% if field.errors -%}
                <span class="help-block">
            {%- for error in field.errors %}
                {{ error }}
            {%- endfor -%}
            </span>
            {% endif %}
        {% endfor -%}
    </form>
{% endblock %}

{% block content %}
    <h2>{{ _("Current workers") }}</h2>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>{{ _("Name") }}</th>
            <th>{{ _("Address") }}</th>
            <th>{{ _("Account No.") }}</th>
            <th>{{ _("National ID") }}</th>
            <th>Norlønn</th>
        </tr>
        </thead>
        <tbody>
        {% for worker in active_workers %}
            <tr>
                <th><a href="{{ worker.get_absolute_url() }}">{{ worker.name }}</a></th>
                <th>{{ worker.address }}</th>
                <th>{{ worker.account_no }}</th>
                <th>{% if worker.person_id %} {{ _("Yes") }}{% else %} {{ _("No") }} {% endif %}</th>
                <th>{{ worker.norlonn_number }}</th>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <h2>{{ _("List of inactive workers") }}</h2>
    {% if inactive_workers -%}
        <table class="table table-striped">
            <thead>
            <tr>
                <th>{{ _("Name") }}</th>
                <th>{{ _("Address") }}</th>
                <th>{{ _("Account No.") }}</th>
                <th>{{ _("National ID") }}</th>
                <th>Norlønn</th>
            </tr>
            </thead>
            <tbody>
            {% for worker in inactive_workers %}
                <tr>
                    <th><a href="{{ worker.get_absolute_url() }}">{{ worker.name }}</a></th>
                    <th>{{ worker.address }}</th>
                    <th>{{ worker.account_no }}</th>
                    <th>{% if worker.person_id %} {{ _("Yes") }}{% else %} {{ _("No") }} {% endif %}</th>
                    <th>{{ worker.norlonn_number }}</th>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {%- else -%}
        <div class="alert alert-info">
            <p>
                <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                <span class="sr-only">Info: </span>
                {% trans %}
                    Your society doesn't seem to have any inactive workers. That's great! :-)
                {% endtrans %}</p>
        </div>
    {%- endif %}
{% endblock %}

templates/workers/view.jinja
{% extends "base.jinja" %}
{% set title = _("Worker") %}
{# Translators: small title for viewing a worker #}
{% set title_small = _("Viewing ""%(name)s"" (#%(id)i)", name=object.name, id=object.id) %}

{% from 'utils.jinja' import table_of_shifts %}

{% macro field(title, value) -%}
    <tr>
        <th class="col-sm-4">{{ title }}</th>
        <td>{{ value }}</td>
    </tr>
{%- endmacro %}


{% block toolbar %}
    <a href="{{ url('worker-edit', object.id) }}" class="btn btn-small btn-warning">
        {{ _("Edit worker") }}
    </a>
    {%- if worker.shifts.count() == 0 %}
    <a href="{{ url('worker-delete', object.id) }}" class="btn btn-small btn-danger">
        {{ _("Delete worker") }}
    </a>
    {%- endif %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-7">
            <h2>{{ _("Personalia") }}</h2>
            <table class="table table-bordered table-striped table-responsive">
                <tbody>
                {{ field(_("Name"), object.name) }}
                {{ field(_("Address"), object.address) }}
                {{ field(_("Societies"), object.societies.all() | join(", ")) }}
                {{ field(_("Norlønn number"), object.norlonn_number) }}
                {{ field(_("Account No."), object.account_no) }}
                {{ field(_("National ID"), object.person_id) }}
                </tbody>
            </table>
        </div>
        <div class="col-md-5">
            <h2>{{ _("Employee details") }}</h2>
                <div class="alert-info alert">
                    <p>{% trans invoices = url('invoices') -%}
                        <em>What do you want to see here?</em>
                    {% endtrans %}</p>
                </div>
        </div>
    </div>

    <h2>{{ _("Shifts") }}</h2>
    {{ table_of_shifts(object.shifts.all(), payroll=True, pov='worker') }}

{% endblock %}